discord:
  token: MTMxNDMzNzkzMTEyMDQ4MDMwOQ.GZ55M6.Kkbdbbu6kFv0EUYlnFm4WkM1_1ZH-_Gl-zaVbw
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_planer
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
flyway:
  url: jdbc:postgresql://localhost:5432/event_planer
  schemas: public
  user: postgres
  password: postgres
